# Generated by Django 4.1.4 on 2023-01-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='mgr_no',
            field=models.IntegerField(),
        ),
    ]
